import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebars: SidebarsConfig = {
  guideSidebar: [
    {
      type: "doc",
      id: "index",
      label: "Introduction",
    },
    {
      type: "category",
      label: "Getting Started",
      collapsed: false,
      items: [
        "getting-started/installation",
        "getting-started/configuration",
        "getting-started/route-handler",
        "getting-started/proxy",
      ],
    },
    {
      type: "category",
      label: "Usage",
      collapsed: false,
      items: [
        "usage/client-components",
        "usage/server-components",
        "usage/protecting-api-routes",
      ],
    },
    {
      type: "doc",
      id: "roadmap",
      label: "Roadmap",
    },
  ],
  apiSidebar: [
    {
      type: "autogenerated",
      dirName: "api",
    },
  ],
};

export default sidebars;
