name: Publish to npm

on:
  push:
    tags:
      - "v*"

# https://docs.npmjs.com/trusted-publishers#step-2-configure-your-cicd-workflow
permissions:
  contents: read
  id-token: write

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-node@v6
        with:
          node-version: 22

      - name: Upgrade npm
        run: npm install -g npm@11.6.2

      - name: Install dependencies
        run: npm ci

      - name: Typecheck
        run: npm run typecheck

      - name: Test
        run: npm test

      - name: Build
        run: npm run build

      - name: Publish
        run: ./scripts/npm-publish.sh
        env:
          GITHUB_REF_NAME: ${{ github.ref_name }}
